Repository AY2122S2-TIC4002-F18-3/tp2, pull requests merged in 2022-03, with the labels that each got.

#28 Update docs
  docs/DeveloperGuide.md
  docs/index.md
Labels: documentation

#37 Feature/record birthday
  data/addressbook.json
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Birthday.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonCard.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Story

#38 create filter command to filter person with specified tag
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/person/NameContainsTagPredicate.java
Labels: type.Enhancement

#45 Add Edit Birthday Feature
  build.gradle
  data/addressbook.json
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
Labels: type.Story, type.Task

#50 Bug 49 fix sample data
  .gitignore
  data/addressbook.json
  docs/team/[TIC4002-F18-3][Li Shihao]PPP.md
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/resources/images/address_book_32--.png
  src/main/resources/images/address_book_32-.png
  src/main/resources/images/address_book_32.png
  src/main/resources/view/MainWindow.fxml
Labels: priority.High, type.Bug

#59 enhance RenameCommand to rename from one tag into N tag
  src/main/java/seedu/address/logic/commands/RenameCommand.java
  src/main/java/seedu/address/logic/parser/RenameCommandParser.java
Labels: priority.Medium

#61 update successful message
  src/main/java/seedu/address/logic/commands/RenameCommand.java
Labels: priority.Low, severity.Low

#58 Dev-47-ft-relation
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RelateCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RelateCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/RelateToPersonPredicate.java
  src/main/java/seedu/address/model/person/Relation.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/resources/view/PersonCard.fxml
  src/test/java/seedu/address/logic/parser/RelateCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Story, priority.High

#65 Feature/sorting
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: type.Story, type.Bug

#97 add in validation for same tag renaming
  src/main/java/seedu/address/logic/commands/RenameCommand.java
  src/main/java/seedu/address/logic/parser/RenameCommandParser.java
Labels: type.Enhancement, priority.High, type.Bug, severity.High

#99 Fix help window URL for UG
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Bug

#100 Fix UG errors in table
  docs/UserGuide.md
  docs/team/[TIC4002-F18-3][Li Shihao]PPP.md
Labels: type.Bug, documentation

#101 fix documentation and message prompt
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/RenameCommand.java
Labels: priority.Medium, type.Bug, severity.VeryLow

#102 validate birthday month
  src/main/java/seedu/address/logic/commands/BirthdayCommand.java
  src/main/java/seedu/address/logic/parser/BirthdayCommandParser.java
Labels: priority.Medium

#103 enhance message to show number of person or contact being renamed
  src/main/java/seedu/address/logic/commands/RenameCommand.java
Labels: priority.Medium, severity.VeryLow
