Repository AY2122S2-TIC4002-F18-3/tp2, pull requests merged in 2022-04, with the labels that each got.

#104 Modify Copy format for Birthday
  src/main/java/seedu/address/model/person/Person.java
Labels: type.Bug, severity.Medium

#109 Fix not saved after add person
  docs/team/l-shihao.md
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
Labels: type.Bug, severity.High

#111 update documentation PPP
  docs/team/yinyin377.md
Labels: documentation

#112 add test case for filter command
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
Labels: type.Task

#113 Add PPP Draft
  docs/team/jr-mojito.md
Labels: documentation

#118 add BirthdayCommandTest
  src/test/java/seedu/address/logic/commands/BirthdayCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
Labels: priority.Medium

#119 adding ParserTest
  src/test/java/seedu/address/logic/parser/BirthdayCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/RenameCommandParserTest.java
Labels: priority.Medium

#125 Update DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/RelateSeqDiag.puml
  docs/images/RelateSeqDiag.png
  docs/images/Ui.png
  src/main/java/seedu/address/MainApp.java
Labels: documentation

#128 Update PPP
  docs/AboutUs.md
  docs/team/l-shihao.md
Labels: documentation
